### ISSUE TITLE
Not updating when passing new data

### ISSUE THREAD

**Issue by nilssonan** [y-takey/chartjs-plugin-stacked100#10]
Using stacked horizontal bars. When updating datasets bars are not redrawing. If i disable the plugin the bars updates as expected.

**Comment by y-takey** [comment]
Hi @nilssonan ,

Thanks for your report, and sorry for the delay.
I've fixed this issue :) Could you try after update the plugin?

**Comment by smcguinness** [comment]
I'm not sure if this is related, however, when I update the data, my data order is being reversed from the original dataset order.

**Comment by y-takey** [comment]
Hi @smcguinness ,
Thank you, It seems related to #12 probably. Could you retry it?

**Comment by smcguinness** [comment]
It appears to still be happening to me. I'm in the middle of a prod deploy, however, I'll do better and get an example to make sure I can isolate the issue before making you waste additional time looking at it. Thanks for jumping on this and #12! 💯

**Comment by smcguinness** [comment]
[JSFiddle](https://jsfiddle.net/dv4nLo1c/)

I couldn't recreate it outside of my project as you can see from the Fiddle above, though it is still happening in my project. Caveat is I'm using React-Chart-2.0 and not the pure ChartJS implementation. I'd say it could be related to something else - at least that is my best guess until I find otherwise. 

Feel free to close this and if I discover more, I'll open another issue. Thanks!

**Comment by av01d** [comment]
Calling `chartInstance.update()` on a chart with `stacked100: { enable: true, replaceTooltipLabel: false }` enabled causes the chart to revert to a normal bar chart; it's not longer stacked.
